### ISSUE TITLE
Should include a link to the extension in the Marketplace 

### ISSUE THREAD

**Issue by gesslar** [tsathoqqua/lima#26]
https://github.com/tsathoqqua/lima/blob/2d42e8b8e79df3535f7bf97c3dcee07ed58b9ccf/lib/help/wizard/coding/vs_code#L20

**Comment by tsathoqqua** [comment]
Fixed in file. Links to https://github.com/jbockle/format-files, is that what you meant?

**Comment by gesslar** [comment]
I mean the marketplace link: https://marketplace.visualstudio.com/items?itemName=jbockle.jbockle-format-files

**Comment by tsathoqqua** [comment]
Fixed.
