### ISSUE TITLE
ANSI_D improvements

### ISSUE THREAD

**Issue by tsathoqqua** [tsathoqqua/lima#3]
Implements some form of [rgb] tuples where r.g. and b are 0-9. Loosely based on some of Gesslars's code. Just smarter as code usually turns out when you do a version 2 :-)

**Comment by gesslar** [comment]
I think 256 is sufficient. 16M is overkill and probably a bit too unwieldy for practical use. Thoughts?

**Comment by tsathoqqua** [comment]
256 is most excellent.  Don't think the human eye can even see 16.7 mio.
