### ISSUE TITLE
Autodoc, which runs at boot time, is getting permission denied creating directories

### ISSUE THREAD

**Issue by gesslar** [tsathoqqua/lima#30]
The permission denied is because `/lib/secure/daemons/secure_d.c`:`check_privilege` does not have a `this_user()`.

```
]Permission denied: /help/autodoc.
]Permission denied: /help/autodoc/FIXME.
]Permission denied: /help/autodoc/command.
]Permission denied: /help/autodoc/examples.
]Permission denied: /help/autodoc/functions.
]Permission denied: /help/autodoc/hook.
]Permission denied: /help/autodoc/modules.
]Permission denied: /help/autodoc/todo.
]Permission denied: /help/autodoc/lima.
```

https://github.com/tsathoqqua/lima/blob/705581adc9a0addb9411c53577e2b34eb3d15028/lib/secure/daemons/secure_d.c#L901

I am not going to fix this. This seems more like an architectural decision. But, I thought  I would bring it to your attention.

**Comment by tsathoqqua** [comment]
These folders used to be just be in GIT, even if the daemon was supposed to create them at first run. Time to get this fixed I guess.

**Comment by tsathoqqua** [comment]
This now get's intercepted by this message:

]Permission denied: /help/autodoc.

]*** Run '@DOC_D->complete_rebuild()' as an admin to initiate the autodoc system.

So you're getting told what to do. I'd rather not have the directories in github, and I'd rather not turn DOC_D into a secure daemon either. So letting the admin initiate the system and until then it'll lay dormant and wait.
